name: Run Python Script

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Python Environment
      run: |
        python --version
        pip list

    - name: Execute Python Script
      env:
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        refresh_access_token: ${{ secrets.REFRESH_ACCESS_TOKEN }}
        top50_tracks_short_id: ${{ secrets.TOP50_TRACKS_SHORT_ID }}

      run: python main.py
      
